### ISSUE TITLE
Create a release each time the IR files are changed

### ISSUE THREAD

**Issue by Panquesito7** [julelang/julec-ir#1]
### Description

I believe creating a release each time the files are updated should be made, as there could be people that want to use a specific version.
Yes, commits are a thing, but releases are easier to manage and use, both for maintainers and other users.

What do you think? Thanks. 🙂

**Comment by mertcandav** [comment]
It is unclear exactly when the IR codes will be updated. I think we can do this with a CD. But the real question is, typically you always want to use the most up-to-date IR code, do we really need to keep track of versions?

If we can handle this with a CD, it's not much of a problem. But basically releases also contain only one IR code. I think there is no problem for now to keep it in the repository instead of presenting it as a release.

**Comment by Panquesito7** [comment]
That's right, I'll be closing this issue. Thank you. 🙂
