### ISSUE TITLE
[FEAT] Create a CI workflow to automatically build the IR files

### ISSUE THREAD

**Issue by Panquesito7** [julelang/julec-ir#2]
### Description

Currently, the IR files are being updated manually, which means the files won't be updated immediately each time a new commit is made. It'd be great if a CI workflow was made to automatically update the IR files. This will also help in actions such as [Setup Jule](https://github.com/Panquesito7/setup-jule.git).

**Comment by mertcandav** [comment]
I think the IR updates should be manual. But I think a script or something like that can be done to speed up this process. That's why I developed a Pure Jule IR updater, currently available in the repository.

IR codes will continue to be updated manually, but the process can now be completed automatically with an executed program. This way, we won't lose our control over IR updates while saving time.

Thanks for your contribution.
